# WARNING: this is only for testing purposes. Do not install in a production
# cluster.
#
# This exposes the hostpath's Unix domain csi.sock as a TCP port to the
# outside world. The mapping from Unix domain socket to TCP is done
# by socat.
#
# This is useful for testing with csi-sanity or csc.

apiVersion: v1
kind: Service
metadata:
  name: hostpath-service
  labels:
    app.kubernetes.io/instance: csi.pos.io
    app.kubernetes.io/part-of: poscsi
    app.kubernetes.io/name: csi-pos-socat
    app.kubernetes.io/component: socat
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: csi.pos.io
    app.kubernetes.io/part-of: poscsi
    app.kubernetes.io/name: csi-pos-socat
    app.kubernetes.io/component: socat
  ports:
   - protocol: TCP
     name: nodeport
     port: 10000 # fixed port inside the pod, dynamically allocated port outside
   - protocol: TCP
     name: controllerport
     port: 20000
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-pos-socat
  labels:
    app.kubernetes.io/instance: csi.pos.io
    app.kubernetes.io/part-of: poscsi
    app.kubernetes.io/name: csi-pos-socat
    app.kubernetes.io/component: socat
spec:
  serviceName: "csi-pos-socat"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: csi.pos.io
      app.kubernetes.io/part-of: poscsi
      app.kubernetes.io/name: csi-pos-socat
      app.kubernetes.io/component: socat
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: csi.pos.io
        app.kubernetes.io/part-of: poscsi
        app.kubernetes.io/name: csi-pos-socat
        app.kubernetes.io/component: socat
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - csi.pos.io
            topologyKey: kubernetes.io/hostname
      containers:
        - name: socat
          image: alpine/socat:1.0.3
          args:
            - tcp-listen:10000,fork,reuseaddr
            - unix-connect:csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
        - name: socat-controller
          image: alpine/socat:1.0.3
          args:
            - tcp-listen:20000,fork,reuseaddr
            - unix-connect:csi/csi-provisioner.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi.pos.io
            type: DirectoryOrCreate
          name: socket-dir

