# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation

{{- if .Values.externallyManagedSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: spdkcsi-secret
stringData:
  secret.json: |-
{{ toJson .Values.csiSecret | indent 4 -}}
{{- end }}
