# Dockerfile-flask
# We simply inherit the Python 3 image. This image does
# not particularly care what OS runs underneath
#FROM tiangolo/uwsgi-nginx-flask:python3.7
FROM python:latest
# Set an environment variable with the directory
# where we'll be running the app
ENV APP /app
ENV PYTHONUNBUFFERED 1
ENV PYTHONIOENCODING UTF-8
# Create the directory and instruct Docker to operate
# from there from now on
#RUN rm  -r /app
#RUN mkdir $APP
WORKDIR $APP/
#WORKDIR /usr/app/
#COPY /app /usr/app/
# Expose the port uWSGI will listen on
EXPOSE 5000
#EXPOSE 8086
#EXPOSE 8888
#EXPOSE 9092
#RUN apt update
#RUN apt install python3-pip python3-dev build-essential python3-setuptools
#ENV FLASK_APP ./rest/app.py
#ENV FLASK_RUN_HOST 0.0.0.0
# Copy the requirements file in order to install
# Python dependencies
COPY ./requirements.txt .
# Install Python dependencies
#RUN  unset -v PYTHONPATH
#RUN sudo apt-get install python3-pip
#RUN pip3 install --upgrade setuptools
RUN apt-get update && apt-get -y install sudo 
RUN pip3 install --upgrade pip
RUN pip3 install -r ./requirements.txt 
RUN pip3 install uwsgi -t ./
# We copy the rest of the codebase into the image
COPY . .
ENV PYTHONPATH "${PYTHONPATH}:./scripts"
#RUN ls -a /root/app
ENTRYPOINT ["./scripts/server_run.sh"]
