version: "3.8"
services:
  
  pos:
    build: 
      context: ./pos
    image: pos:1.0.0
    network_mode: host
    privileged: true
    hostname: vm-ibof-target
    tty: true
    stdin_open: true
    cap_add:
      - ALL
    volumes:
      - /sys:/sys 
      - /dev:/dev 
      - /usr/src:/usr/src 
      - /lib/modules:/lib/modules
  
  initiator:
    build: 
      context: ./initiator
    image: initiator:1.0.0
    network_mode: host
    privileged: true
    hostname: vm-ibof-target
    tty: true
    stdin_open: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev 

  m9k:
    build: 
      context: ./m9k
    image: m9k:1.0.0
    network_mode: host
    privileged: true
    hostname: vm-ibof-target
    tty: true
    stdin_open: true
    cap_add:
      - ALL
