# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spdkcsi-pvc-block
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 256Mi
  storageClassName: spdkcsi-sc

---
kind: Pod
apiVersion: v1
metadata:
  name: spdkcsi-test-block
spec:
  containers:
  - name: ubuntu
    image: ubuntu:18.04
    imagePullPolicy: "IfNotPresent"
    command: ["sleep", "365d"]
    volumeDevices:
    - devicePath: /dev/xdb
      name: spdk-volume
  volumes:
  - name: spdk-volume
    persistentVolumeClaim:
      claimName: spdkcsi-pvc-block
