# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
kind: Secret
metadata:
  name: poscsi-secret
stringData:
  # Specify node specific token with item "name" matches ConfigMap.
  # {
  #   "name": "pos-testnode",
  #   "username": "myuser",
  #   "password": "mypass"
  # }
  secret.json: |-
    {
      "rpcTokens": [
        {
          "name": "localhost",
          "username": "poscsiuser",
          "password": "poscsipass"
        }
      ]
    }
