# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation

# Snapshot API version compatibility:
# v1beta1:
#   v1.17 =< k8s < v1.20
#   2.x =< snapshot-controller < v4.x
# We recommend to use {sidecar, controller, crds} of same version
---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: csi-spdk-snapclass
driver: csi.spdk.io
deletionPolicy: Delete
