# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: poscsi-sc
provisioner: csi.pos.io
parameters:
  fsType: ext4
  transportType: "tcp"
  targetAddress: "107.108.83.97"
  transportServiceId: "1158"
  provisionerIP: "107.108.83.97"
  provisionerPort: "3003"
  nqnName: "nqn.2019-04.pos:subsystem1"
  arrayName: "POSArray"
reclaimPolicy: Delete
volumeBindingMode: Immediate
