/* -------------------------------------------------------------------------------------/
                                                                                    /
/               COPYRIGHT (c) 2019 SAMSUNG ELECTRONICS CO., LTD.                      /
/                          ALL RIGHTS RESERVED                                        /
/                                                                                     /
/   Permission is hereby granted to licensees of Samsung Electronics Co., Ltd.        /
/   products to use or abstract this computer program for the sole purpose of         /
/   implementing a product based on Samsung Electronics Co., Ltd. products.           /
/   No other rights to reproduce, use, or disseminate this computer program,          /
/   whether in part or in whole, are granted.                                         / 
/                                                                                     /
/   Samsung Electronics Co., Ltd. makes no representation or warranties with          /
/   respect to the performance of this computer program, and specifically disclaims   /
/   any responsibility for any damages, special or consequential, connected           /
/   with the use of this program.                                                     /
/                                                                                     /
/-------------------------------------------------------------------------------------/


DESCRIPTION: <Exporting all actions from this file> *
@NAME : actionTypes.js
@AUTHORS: Jay Hitesh Sanghavi, Palak Kapoor
@Version : 1.0 *
@REVISION HISTORY
[03/06/2019] [Jay] : Prototyping..........////////////////////
[07/08/2019] [Palak] : Prototyping..........////////////////////
*/

// HEADER COMPONENT
export const GET_IS_IBOF_OS_RUNNING = "GET_IS_IBOF_OS_RUNNING"

export const SAGA_GET_IS_IBOF_OS_RUNNING = "SAGA_GET_IS_IBOF_OS_RUNNING"

export const UPDATE_TIMESTAMP = "UPDATE_TIMESTAMP"

export const SAGA_UPDATE_TIMESTAMP = "SAGA_UPDATE_TIMESTAMP"

// DASHBOARD PAGE
export const ENABLE_FETCHING_ALERTS = "ENABLE_FETCHING_ALERTS" // No SAGA action for this. Only applicable for sync call

export const FETCH_VOLUME_INFO = "FETCH_VOLUME_INFO"

export const SAGA_FETCH_VOLUME_INFO = "SAGA_FETCH_VOLUME_INFO"

export const FETCH_PERFORMANCE_INFO = "FETCH_PERFORMANCE_INFO"

export const SAGA_FETCH_PERFORMANCE_INFO = "SAGA_FETCH_PERFORMANCE_INFO"

export const FETCH_ALERTS_INFO = "FETCH_ALERTS_INFO"

export const SAGA_FETCH_ALERTS_INFO = "SAGA_FETCH_ALERTS_INFO"

export const FETCH_STORAGE_INFO = "FETCH_STORAGE_INFO"

export const SAGA_FETCH_STORAGE_INFO = "SAGA_FETCH_STORAGE_INFO"

export const FETCH_IPANDMAC_INFO = "FETCH_IPANDMAC_INFO"

export const SAGA_FETCH_IPANDMAC_INFO = "SAGA_FETCH_IPANDMAC_INFO"

// Storage Actions
export const CLEAR_VOLUMES = "CLEAR_VOLUMES"

export const FETCH_VOLUMES = "FETCH_VOLUMES"

export const SAGA_FETCH_VOLUMES="SAGA_FETCH_VOLUMES"

export const FETCH_DEVICE_INFO = "FETCH_DEVICE_INFO"

export const SAGA_FETCH_DEVICE_INFO = "SAGA_FETCH_DEVICE_INFO"

export const FETCH_DEVICE_DETAILS = "FETCH_DEVICE_DETAILS"

export const SAGA_FETCH_DEVICE_DETAILS = "SAGA_FETCH_DEVICE_DETAILS"

export const SAGA_ATTACH_DISK = "SAGA_ATTACH_DISK"

export const SAGA_DETACH_DISK = "SAGA_DETACH_DISK"

export const SAGA_ADD_SPARE_DISK = "SAGA_ADD_SPARE_DISK"

export const SAGA_REMOVE_SPARE_DISK = "SAGA_REMOVE_SPARE_DISK"

export const SAVE_VOLUME = "SAVE_VOLUME"

export const SAGA_SAVE_VOLUME = "SAGA_SAVE_VOLUME"

export const DELETE_VOLUMES = "DELETE_VOLUMES"

export const SAGA_DELETE_VOLUMES = "SAGA_DELETE_VOLUMES"

export const FETCH_ARRAY = "FETCH_ARRAY"

export const SAGA_FETCH_ARRAY = "SAGA_FETCH_ARRAY"

export const CREATE_ARRAY = "CREATE_ARRAY"

export const SAGA_CREATE_ARRAY = "SAGA_CREATE_ARRAY"

export const SAGA_DELETE_ARRAY = "SAGA_DELETE_ARRAY"

export const FETCH_ARRAY_SIZE = "FETCH_STORAGE_SIZE"

export const SAGA_FETCH_ARRAY_SIZE = "FETCH_ARRAY_SIZE"

export const SET_NO_ARRAY = "SET_NO_ARRAY"

export const SELECT_VOLUME = "SELECT_VOLUME"

export const EDIT_VOLUME = "EDIT_VOLUME"

export const ADD_VOLUME = "ADD_VOLUME"

export const CHANGE_VOLUME_FIELD = "CHANGE_VOLUME_FIELD"

export const SAGA_UPDATE_VOLUME = "SAGA_UPDATE_VOLUME"

export const FETCH_VOL_READ_BW = "FETCH_VOL_READ_BW"

export const FETCH_VOL_WRITE_BW = "FETCH_VOL_WRITE_BW"

export const FETCH_VOL_READ_IOPS = "FETCH_VOL_READ_IOPS"

export const FETCH_VOL_WRITE_IOPS = "FETCH_VOL_WRITE_IOPS"

export const FETCH_VOL_LATENCY = "FETCH_VOL_LATENCY"

export const SELECT_ALL_VOLUMES = "SELECT_ALL_VOLUMES"

export const STORAGE_SHOW_ALERT = "STORAGE_SHOW_ALERT"

export const STORAGE_CLOSE_ALERT = "STORAGE_CLOSE_ALERT"

export const STORAGE_START_LOADER = "STORAGE_START_LOADER"

export const STORAGE_STOP_LOADER = "STORAGE_STOP_LOADER"

export const START_LOADER = "START_LOADER"

export const STOP_LOADER = "STOP_LOADER"

export const FETCH_MAX_VOLUME_COUNT = "FETCH_MAX_VOLUME_COUNT"

export const SAGA_FETCH_MAX_VOLUME_COUNT = "SAGA_FETCH_MAX_VOLUME_COUNT"

export const TOGGLE_CREATE_VOLUME_BUTTON = "TOGGLE_CREATE_VOLUME_BUTTON"

// Performance Page Actions
export const FETCH_DISK_USED = "FETCH_DISK_USED"

export const SAGA_FETCH_DISK_USED = "SAGA_FETCH_DISK_USED"

export const FETCH_DISK_WRITE = "FETCH_DISK_WRITE"

export const SAGA_FETCH_DISK_WRITE = "SAGA_FETCH_DISK_WRITE"

export const FETCH_CPU_USAGE = "FETCH_CPU_USAGE"

export const SAGA_FETCH_CPU_USAGE = "SAGA_FETCH_CPU_USAGE"

export const FETCH_READ_BANDWIDTH = "FETCH_READ_BANDWIDTH"

export const SAGA_FETCH_READ_BANDWIDTH = "SAGA_FETCH_READ_BANDWIDTH"

export const FETCH_WRITE_BANDWIDTH = "FETCH_WRITE_BANDWIDTH"

export const SAGA_FETCH_WRITE_BANDWIDTH = "SAGA_FETCH_WRITE_BANDWIDTH"

export const FETCH_READ_IOPS = "FETCH_READ_IOPS"

export const SAGA_FETCH_READ_IOPS = "SAGA_FETCH_READ_IOPS"

export const FETCH_WRITE_IOPS = "FETCH_WRITE_IOPS"

export const SAGA_FETCH_WRITE_IOPS = "SAGA_FETCH_WRITE_IOPS"

export const FETCH_INPUT_POWER_VARIATION = "FETCH_INPUT_POWER_VARIATION"

export const SAGA_FETCH_INPUT_POWER_VARIATION = "SAGA_FETCH_INPUT_POWER_VARIATION"

export const RESET_PERF_STATE = "RESET_PERF_STATE"

export const FETCH_LATENCY = "FETCH_LATENCY"

export const SAGA_FETCH_LATENCY = "SAGA_FETCH_LATENCY"

// Language Change
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE"

//  CONFIGURATION SETTING PAGE
export const CHANGE_EMAIL_LIST = "CHANGE_EMAIL_LIST"

export const SET_ALERT_BOX = "SET_ALERT_BOX"

export const FETCH_EMAIL_LIST = "FETCH_EMAIL_LIST"

export const SAGA_FETCH_EMAIL_LIST = "SAGA_FETCH_EMAIL_LIST"

export const UPDATE_EMAIL = "UPDATE_EMAIL"

export const SAGA_UPDATE_EMAIL = "SAGA_UPDATE_EMAIL"

export const TOGGLE_ACTIVE_STATUS = "TOGGLE_ACTIVE_STATUS"

export const SAGA_TOGGLE_ACTIVE_STATUS = "SAGA_TOGGLE_ACTIVE_STATUS"

export const SAGA_SEND_EMAIL = "SAGA_SEND_EMAIL"

export const SAGA_TEST_EMAIL = "SAGA_TEST_EMAIL"

export const CHANGE_SMTP_SERVER = "CHANGE_SMTP_SERVER"

export const SET_SMTP_SERVER = "SET_SMTP_SERVER"

export const DELETE_CONFIGURED_SMTP_SERVER = "DELETE_CONFIGURED_SMTP_SERVER"

export const SAGA_DELETE_EMAIL_IDS = "SAGA_DELETE_EMAIL_IDS"

export const SAGA_DOWNLOAD_LOGS = "SAGA_DOWNLOAD_LOGS"

export const SET_IBOFOS_TIME_INTERVAL = "SET_IBOFOS_TIME_INTERVAL" // Pure Action

export const SAGA_SET_IBOFOS_TIME_INTERVAL = "SAGA_SET_IBOFOS_TIME_INTERVAL"

export const SAGA_GET_IBOFOS_TIME_INTERVAL = "SAGA_GET_IBOFOS_TIME_INTERVAL"

//  Log Management PAGE
export const GET_IBOFOS_LOGS = "GET_IBOFOS_LOGS"

export const SAGA_GET_IBOFOS_LOGS = "SAGA_GET_IBOFOS_LOGS"

export const SAGA_GET_LIVE_LOGS_DB = "SAGA_GET_LIVE_LOGS_DB"

export const SAGA_SET_LIVE_LOGS_DB = "SAGA_SET_LIVE_LOGS_DB"

export const SET_LIVE_LOGS = "SET_LIVE_LOGS"

// Alert Management
export const ALERT_MANAGEMENT_SET_ALERTS = "ALERT_MANAGEMENT_SET_ALERTS" // No SAGA action for this. Only applicable for sync call

export const ALERT_MANAGEMENT_OPEN_ALERT_BOX = "ALERT_MANAGEMENT_OPEN_ALERT_BOX" // No SAGA action for this. Only applicable for sync call

export const ALERT_MANAGEMENT_FETCH_ALERTS = "ALERT_MANAGEMENT_FETCH_ALERTS"

export const SAGA_ALERT_MANAGEMENT_FETCH_ALERTS = "SAGA_ALERT_MANAGEMENT_FETCH_ALERTS"

export const ALERT_MANAGEMENT_FETCH_ALERTS_TYPE = "ALERT_MANAGEMENT_FETCH_ALERTS_TYPE"

export const SAGA_ALERT_MANAGEMENT_FETCH_ALERTS_TYPE = "SAGA_ALERT_MANAGEMENT_FETCH_ALERTS_TYPE"

export const SAGA_ALERT_MANAGEMENT_UPDATE_ALERTS = "SAGA_ALERT_MANAGEMENT_UPDATE_ALERTS"

export const SAGA_ALERT_MANAGEMENT_DELETE_ALERTS = "SAGA_ALERT_MANAGEMENT_DELETE_ALERTS"

export const SAGA_ALERT_MANAGEMENT_TOGGLE_ALERTS = "SAGA_ALERT_MANAGEMENT_TOGGLE_ALERTS"

export const SAGA_ALERT_MANAGEMENT_ADD_NEW_ALERTS = "SAGA_ALERT_MANAGEMENT_ADD_NEW_ALERTS"

//  Authentication
export const CHANGE_CREDENTIALS = "CHANGE_CREDENTIALS"

export const SAGA_LOGIN = "SAGA_LOGIN"

export const SET_IS_LOGGED_IN = "SET_IS_LOGGED_IN"

export const RESET_IS_LOGGED_IN = "RESET_IS_LOGGED_IN"

export const SET_LOGIN_FAILED = "SET_LOGIN_FAILED"

//  BMC Authentication
export const BMC_CHANGE_CREDENTIALS = "BMC_CHANGE_CREDENTIALS"

export const SAGA_BMC_LOGIN = "SAGA_BMC_LOGIN"

export const BMC_SET_IS_LOGGED_IN = "BMC_SET_IS_LOGGED_IN"

export const BMC_RESET_IS_LOGGED_IN = "BMC_RESET_IS_LOGGED_IN"

export const BMC_SET_LOGIN_FAILED = "BMC_SET_LOGIN_FAILED"

// User Management
export const USER_MANAGEMENT_SET_USERS = "USER_MANAGEMENT_SET_USERS" // No SAGA action for this. Only applicable for sync call

export const USER_MANAGEMENT_OPEN_USER_BOX = "USER_MANAGEMENT_OPEN_USER_BOX" // No SAGA action for this. Only applicable for sync call

export const USER_MANAGEMENT_FETCH_USERS = "USER_MANAGEMENT_FETCH_USERS" 

export const SAGA_USER_MANAGEMENT_FETCH_USERS = "SAGA_USER_MANAGEMENT_FETCH_USERS" 

export const SAGA_USER_MANAGEMENT_UPDATE_USERS = "SAGA_USER_MANAGEMENT_UPDATE_USERS"

export const SAGA_USER_MANAGEMENT_DELETE_USERS = "SAGA_USER_MANAGEMENT_DELETE_USERS"

export const SAGA_USER_MANAGEMENT_TOGGLE_USERS = "SAGA_USER_MANAGEMENT_TOGGLE_USERS"

export const SAGA_USER_MANAGEMENT_ADD_NEW_USERS = "SAGA_USER_MANAGEMENT_ADD_NEW_USERS"

// Hardware Page Actions
export const HARDWARE_OVERVIEW_FETCH_SERVER_INFORMATION = "HARDWARE_OVERVIEW_FETCH_SERVER_INFORMATION"

export const SAGA_HARDWARE_OVERVIEW_FETCH_SERVER_INFORMATION = "SAGA_HARDWARE_OVERVIEW_FETCH_SERVER_INFORMATION"

export const HARDWARE_OVERVIEW_FETCH_POWER_INFORMATION = "HARDWARE_OVERVIEW_FETCH_POWER_INFORMATION"

export const SAGA_HARDWARE_OVERVIEW_FETCH_POWER_INFORMATION = "SAGA_HARDWARE_OVERVIEW_FETCH_POWER_INFORMATION"

export const HARDWARE_OVERVIEW_FETCH_CHASSIS_FRONT_INFORMATION = "HARDWARE_OVERVIEW_FETCH_CHASSIS_FRONT_INFORMATION"

export const SAGA_HARDWARE_OVERVIEW_FETCH_CHASSIS_FRONT_INFORMATION = "SAGA_HARDWARE_OVERVIEW_FETCH_CHASSIS_FRONT_INFORMATION"

export const HARDWARE_OVERVIEW_FETCH_CHASSIS_REAR_INFORMATION = "HARDWARE_OVERVIEW_FETCH_CHASSIS_REAR_INFORMATION"

export const SAGA_HARDWARE_OVERVIEW_FETCH_CHASSIS_REAR_INFORMATION = "SAGA_HARDWARE_OVERVIEW_FETCH_CHASSIS_REAR_INFORMATION"

export const HARDWARE_OVERVIEW_REBOOT_SYSTEM = "HARDWARE_OVERVIEW_REBOOT_SYSTEM"

export const SAGA_HARDWARE_OVERVIEW_REBOOT_SYSTEM = "SAGA_HARDWARE_OVERVIEW_REBOOT_SYSTEM"

export const HARDWARE_OVERVIEW_SHUTDOWN_SYSTEM = "HARDWARE_OVERVIEW_SHUTDOWN_SYSTEM"

export const SAGA_HARDWARE_OVERVIEW_SHUTDOWN_SYSTEM = "SAGA_HARDWARE_OVERVIEW_SHUTDOWN_SYSTEM"

export const SAGA_HARDWARE_OVERVIEW_FORCE_SHUTDOWN_SYSTEM = "SAGA_HARDWARE_OVERVIEW_FORCE_SHUTDOWN_SYSTEM"

export const SAGA_HARDWARE_OVERVIEW_POWER_ON_SYSTEM = "SAGA_HARDWARE_OVERVIEW_POWER_ON_SYSTEM"

export const SAGA_HARDWARE_SENSORS_FETCH_POWER_SENSOR_INFORMATION = "SAGA_HARDWARE_SENSORS_FETCH_POWER_SENSOR_INFORMATION"

export const HARDWARE_SENSORS_FETCH_POWER_SENSOR_INFORMATION = "HARDWARE_SENSORS_FETCH_POWER_SENSOR_INFORMATION"

export const SAGA_HARDWARE_SENSORS_FETCH_FAN_SENSOR_INFORMATION = "SAGA_HARDWARE_SENSORS_FETCH_FAN_SENSOR_INFORMATION"

export const HARDWARE_SENSORS_FETCH_FAN_SENSOR_INFORMATION = "HARDWARE_SENSORS_FETCH_FAN_SENSOR_INFORMATION"

export const SAGA_HARDWARE_SENSORS_FETCH_TEMPERATURE_SENSOR_INFORMATION = "SAGA_HARDWARE_SENSORS_FETCH_TEMPERATURE_SENSOR_INFORMATION"

export const HARDWARE_SENSORS_FETCH_TEMPERATURE_SENSOR_INFORMATION = "HARDWARE_SENSORS_FETCH_TEMPERATURE_SENSOR_INFORMATION"

export const SAGA_HARDWARE_HEALTH_FETCH_SOFTWARE_DETAILS= "SAGA_HARDWARE_HEALTH_FETCH_SOFTWARE_DETAILS"

export const HARDWARE_HEALTH_FETCH_SOFTWARE_DETAILS= "HARDWARE_HEALTH_FETCH_SOFTWARE_DETAILS"

export const SAGA_HARDWARE_HEALTH_FETCH_HARDWARE_DETAILS= "SAGA_HARDWARE_HEALTH_FETCH_HARDWARE_DETAILS"

export const HARDWARE_HEALTH_FETCH_HARDWARE_DETAILS= "HARDWARE_HEALTH_FETCH_HARDWARE_DETAILS"

export const SAGA_HARDWARE_HEALTH_FETCH_NETWORK_DETAILS= "SAGA_HARDWARE_HEALTH_FETCH_NETWORK_DETAILS"

export const HARDWARE_HEALTH_FETCH_NETWORK_DETAILS= "HARDWARE_HEALTH_FETCH_NETWORK_DETAILS"

export const SAGA_HARDWARE_POWER_MANAGEMENT_FETCH_POWER_SUMMARY_INFORMATION = "SAGA_HARDWARE_POWER_MANAGEMENT_FETCH_POWER_SUMMARY_INFORMATION"

export const HARDWARE_POWER_MANAGEMENT_FETCH_POWER_SUMMARY_INFORMATION = "HARDWARE_POWER_MANAGEMENT_FETCH_POWER_SUMMARY_INFORMATION"

export const SAGA_HARDWARE_POWER_MANAGEMENT_SET_CURRENT_POWER_MODE = "SAGA_HARDWARE_POWER_MANAGEMENT_SET_CURRENT_POWER_MODE"

export const SAGA_HARDWARE_POWER_MANAGEMENT_CHANGE_CURRENT_POWER_STATE = "SAGA_HARDWARE_POWER_MANAGEMENT_CHANGE_CURRENT_POWER_STATE"



