name: UnitTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ["3.6.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Installing packages ...
      run: |
        cd src/mtool/api
        pip3 install -r requirements.txt
        pip3 install requests-mock
    - name: Running Unit Tests ...
      run: |
        cd src/mtool/api
        export PYTHONPATH=$PYTHONPATH:$PWD
        pytest -s
